version: '3'
services:
  challenge:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "1337:1337"
    volumes:
      - ./:/home/user
    security_opt:
      - seccomp:unconfined
    privileged: true
    init: true